services:
  nethermind-chiado:
    build:
      context: .
      dockerfile: x64.Dockerfile
    restart: unless-stopped
    networks:
      - circles-chiado
    ports:
      - 30303:30303/tcp # p2p
      - 30303:30303/udp # p2p
      - 8545:8545
    expose:
      - 8551 # engine api
    volumes:
      - .state/nethermind-chiado:/data
      - .state/jwtsecret-chiado/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      --config=chiado
      --datadir=/data
      --log=INFO
      --Sync.SnapSync=false
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,Circles]
      --JsonRpc.JwtSecretFile=/jwt.hex
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --Network.DiscoveryPort=30303
      --HealthChecks.Enabled=false
    env_file:
      - .env
    environment:
      - V1_HUB_ADDRESS=0xdbf22d4e8962db3b2f1d9ff55be728a887e47710
      - V2_HUB_ADDRESS=0xFFfbD3E62203B888bb8E09c1fcAcE58242674964
      - V2_NAME_REGISTRY_ADDRESS=0x0A1D308a39A6dF8972A972E586E4b4b3Dc73520f
      # - START_BLOCK=0
      - POSTGRES_CONNECTION_STRING=Server=postgres-chiado;Port=5432;Database=postgres;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};

  postgres-chiado:
    image: postgres:16
    command: -c 'max_connections=100'
    restart: unless-stopped
    networks:
      - circles-chiado
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./.state/postgres-chiado:/var/lib/postgresql/data

  consensus-chiado:
    container_name: consensus-chiado
    image: sigp/lighthouse:v5.0.0
    restart: always
    networks:
      - circles-chiado
    ports:
      - 9000:9000/tcp # p2p
      - 9000:9000/udp # p2p
      - 5054:5054/tcp # metrics
    expose:
      - 4000 # http
    volumes:
      - .state/consensus-chiado/data:/data
      - .state/jwtsecret-chiado/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse
      beacon_node
      --network=chiado
      --disable-upnp
      --datadir=/data
      --port=9000
      --http
      --http-address=0.0.0.0
      --http-port=4000
      --execution-endpoint=http://nethermind-chiado:8551
      --execution-jwt=/jwt.hex
      --checkpoint-sync-url=https://checkpoint.chiadochain.net/

networks:
  circles-chiado:
    name: circles-chiado
