services:
  nethermind:
    container_name: nethermind
    #image: jaensen/nethermind-circlesubi:dev-x86_64
    build:
      context: .
      dockerfile: x64.Dockerfile
    restart: unless-stopped
    network_mode: host
    ports:
      - 30303:30303/tcp # p2p
      - 30303:30303/udp # p2p
      - 8545:8545
    expose:
      - 8551 # engine api
    volumes:
      - .state/gnosis/nethermind:/data
      - .state/gnosis/jwtsecret:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      --config=gnosis
      --datadir=/data
      --log=INFO
      --Sync.SnapSync=false
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,Circles]
      --JsonRpc.JwtSecretFile=/jwt.hex
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --Network.DiscoveryPort=30303
      --HealthChecks.Enabled=false
    logging:
      driver: "local"
    environment:
      - V1_HUB_ADDRESS=0x29b9a7fBb8995b2423a71cC17cf9810798F6C543
      - V2_HUB_ADDRESS=0xDA02CDB5279B3a1eF27Be3d91aE924495E6A5569
      - START_BLOCK=0
      - POSTGRES_CONNECTION_STRING=Server=localhost;Port=5432;User Id=postgres;Password=;Database=postgres;Include Error Detail=true;

  db:
    image: postgres:16
    command: -c 'max_connections=100'
    restart: unless-stopped
    container_name: 'postgres'
    network_mode: host
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    volumes:
      - ./.state/gnosis/postgres-data:/var/lib/postgresql/data

  lighthouse:
    container_name: lighthouse
    image: sigp/lighthouse:v5.0.0
    restart: always
    network_mode: host
    ports:
      - 9000:9000/tcp # p2p
      - 9000:9000/udp # p2p
      - 5054:5054/tcp # metrics
    expose:
      - 4000 # http
    volumes:
      - .state/gnosis/lighthouse/data:/data
      - .state/gnosis/jwtsecret:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse
      beacon_node
      --network=gnosis
      --disable-upnp
      --datadir=/data
      --port=9000
      --http
      --http-address=0.0.0.0
      --http-port=4000
      --execution-endpoint=http://localhost:8551
      --execution-jwt=/jwt.hex
      --checkpoint-sync-url=https://checkpoint.gnosis.gateway.fm/
    logging:
      driver: "local"

networks:
  circles:
    name: circles
