namespace Circles.Index.Common;

public enum Columns
{
    [DbIdentifier("organization_name")] OrganizationName,
    [DbIdentifier("block_number")] BlockNumber,
    [DbIdentifier("uri")] Uri,
    [DbIdentifier("group_address")] GroupAddress,
    [DbIdentifier("group_symbol")] GroupSymbol,
    [DbIdentifier("start_period")] StartPeriod,
    [DbIdentifier("transaction_hash")] TransactionHash,
    [DbIdentifier("block_hash")] BlockHash,
    [DbIdentifier("truster_address")] TrusterAddress,
    [DbIdentifier("can_send_to_address")] CanSendToAddress,
    [DbIdentifier("from_address")] FromAddress,
    [DbIdentifier("day")] Day,
    [DbIdentifier("address")] Address,
    [DbIdentifier("token_address")] TokenAddress,
    [DbIdentifier("approved")] Approved,
    [DbIdentifier("inflation_value")] InflationValue,
    [DbIdentifier("limit")] Limit,
    [DbIdentifier("demurrage_value")] DemurrageValue,
    [DbIdentifier("user_address")] UserAddress,
    [DbIdentifier("end_period")] EndPeriod,
    [DbIdentifier("timestamp")] Timestamp,
    [DbIdentifier("amount")] Amount,
    [DbIdentifier("invitee_address")] InviteeAddress,
    [DbIdentifier("operator_address")] OperatorAddress,
    [DbIdentifier("circles_address")] CirclesAddress,
    [DbIdentifier("token_id")] TokenId,
    [DbIdentifier("expiry_time")] ExpiryTime,
    [DbIdentifier("log_index")] LogIndex,
    [DbIdentifier("inviter_address")] InviterAddress,
    [DbIdentifier("organization_address")] OrganizationAddress,
    [DbIdentifier("trustee_address")] TrusteeAddress,
    [DbIdentifier("to_address")] ToAddress,
    [DbIdentifier("group_name")] GroupName,
    [DbIdentifier("transaction_index")] TransactionIndex,
    [DbIdentifier("batch_index")] BatchIndex,
    [DbIdentifier("mint_policy")] MintPolicy,
    [DbIdentifier("treasury")] Treasury,
    [DbIdentifier("human_address")] HumanAddress,
    [DbIdentifier("value")] Value,
    [DbIdentifier("owner")] Owner,
    [DbIdentifier("operator")] Operator
}